language: node_js
node_js:
- '4'
deploy:
  provider: npm
  email: mail@jojow.de
  api_key:
    secure: HCnS/rtlaeDtG/UcdKPnUwX97PXlw7d+vWK1entzJRhh6hqg2zZQSLLVCcnSwMOKc7tSlzbwUP6Duytfd+PWVmYQh8+ChmdWt/UBT+9fJVY1XYHH1S8MbsGD6J/B9Vchg0ND+B8a7YM3CtEB0eM/YcpdbDpiOtU+EOA+tl1Im/k=
